name: Test Lint

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x

      - name: Setup Cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/_config.ts', '**/import_map.json') }}

      - name: Running Tools
        run: |
          deno lint
          deno fmt